# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nidhin D
email: dnidhin5@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Journal</h1><h3>An enthusiastic web developer </h3>



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nidhin.me" # the base hostname & protocol for your site
twitter_username: nidhin_nambiar
github_username:  nidhinnambiar

# Build settings
markdown: kramdown
