# Site settings
title: Nidhin D
description: 'An enthusiastic Ruby developer :)'
url: 'http://nidhin.me'
baseurl: '/'
google_analytics: 'UA-77782492-1'
disqus_shortname: 'nidhin_nambiar'

author:
  name: 'nidhin.me'
  email: touch@nidhin.me
  twitter_username:
  facebook_username:
  github_username:  nidhinnambiar
  linkedin_username:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
